# Yarn Plug'n'Play has some compatibility issues with older versions of tools
# like Webpack that we are still using. `pnpm` mode gives us a lot of the same
# benefits of disk usage and explicit dependency enforcement without those
# compatibility problems.
nodeLinker: pnpm

yarnPath: .yarn/releases/yarn-3.5.0.cjs
