ALTER TABLE `Challenge` DROP FOREIGN KEY `speedRunId_refs_speedRunId_5ab03dfd`;
ALTER TABLE `ChallengeBid` DROP FOREIGN KEY `challengeId_refs_challengeId_602ffc05`;
ALTER TABLE `ChallengeBid` DROP FOREIGN KEY `donationId_refs_donationId_3354ae03`;
ALTER TABLE `Choice` DROP FOREIGN KEY `speedRunId_refs_speedRunId_7b163710`;
ALTER TABLE `ChoiceBid` DROP FOREIGN KEY `donationId_refs_donationId_2c936a46`;
ALTER TABLE `ChoiceBid` DROP FOREIGN KEY `optionId_refs_optionId_24849baa`;
ALTER TABLE `ChoiceOption` DROP FOREIGN KEY `choiceId_refs_choiceId_71efa8d4`;
ALTER TABLE `Donation` DROP FOREIGN KEY `bidState_refs_donationBidStateId_3f1316c5`;
ALTER TABLE `Donation` DROP FOREIGN KEY `commentState_refs_donationCommentStateId_76458b37`;
ALTER TABLE `Donation` DROP FOREIGN KEY `domain_refs_donationDomainId_1ffe7019`;
ALTER TABLE `Donation` DROP FOREIGN KEY `donorId_refs_donorId_4fba4006`;
ALTER TABLE `Donation` DROP FOREIGN KEY `readState_refs_donationReadStateId_65759d57`;
ALTER TABLE `Prize` DROP FOREIGN KEY `donorId_refs_donorId_7981a8f`;
DROP TABLE BidState;
DROP TABLE DonationReadState;
DROP TABLE DonationBidState;
DROP TABLE DonationCommentState;
DROP TABLE DonationDomain;
alter table Donor change donorId id Integer;
alter table Donation change donationId id Integer;
alter table Donation change donorId donor Integer;
alter table SpeedRun change speedRunId id Integer;
alter table Choice change choiceId id Integer;
alter table Choice change speedRunId speedRun Integer;
alter table ChoiceOption change optionId id Integer;
alter table ChoiceOption change choiceId choice Integer;
alter table Challenge change challengeId id Integer;
alter table Challenge change speedRunId speedRun Integer;
alter table ChoiceBid change choiceBidId id Integer;
alter table ChoiceBid change optionId choiceOption Integer;
alter table ChoiceBid change donationId donation Integer;
alter table ChallengeBid change challengeBidId id Integer;
alter table ChallengeBid change challengeId challenge Integer;
alter table ChallengeBid change donationId donation Integer;
alter table Prize change prizeId id Integer;
alter table Prize change donorId winner Integer;
ALTER TABLE `ChallengeBid` ADD CONSTRAINT `challenge_refs_id_602ffc05` FOREIGN KEY (`challenge`) REFERENCES `Challenge` (`id`);
ALTER TABLE `ChoiceOption` ADD CONSTRAINT `choice_refs_id_71efa8d4` FOREIGN KEY (`choice`) REFERENCES `Choice` (`id`);
ALTER TABLE `ChoiceBid` ADD CONSTRAINT `choiceOption_refs_id_24849baa` FOREIGN KEY (`choiceOption`) REFERENCES `ChoiceOption` (`id`);
ALTER TABLE `ChallengeBid` ADD CONSTRAINT `donation_refs_id_3354ae03` FOREIGN KEY (`donation`) REFERENCES `Donation` (`id`);
ALTER TABLE `ChoiceBid` ADD CONSTRAINT `donation_refs_id_2c936a46` FOREIGN KEY (`donation`) REFERENCES `Donation` (`id`);
ALTER TABLE `Donation` ADD CONSTRAINT `donor_refs_id_4fba4006` FOREIGN KEY (`donor`) REFERENCES `Donor` (`id`);
ALTER TABLE `Prize` ADD CONSTRAINT `winner_refs_id_7981a8f` FOREIGN KEY (`winner`) REFERENCES `Donor` (`id`);
ALTER TABLE `Challenge` ADD CONSTRAINT `speedRun_refs_id_5ab03dfd` FOREIGN KEY (`speedRun`) REFERENCES `SpeedRun` (`id`);
ALTER TABLE `Choice` ADD CONSTRAINT `speedRun_refs_id_7b163710` FOREIGN KEY (`speedRun`) REFERENCES `SpeedRun` (`id`);
