# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-19 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_squashed_0020_add_runner_pronouns_and_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='next_run',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', serialize=False, to='tracker.SpeedRun'),
        ),
        migrations.AddField(
            model_name='prize',
            name='prev_run',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', serialize=False, to='tracker.SpeedRun'),
        ),
    ]
