# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-19 03:21
from __future__ import unicode_literals

from django.db import migrations


def populate_prev_next_run(apps, schema_editor):
    # noinspection PyPep8Naming
    Prize = apps.get_model('tracker', 'Prize')
    # noinspection PyPep8Naming
    SpeedRun = apps.get_model('tracker', 'SpeedRun')
    db_alias = schema_editor.connection.alias
    for prize in Prize.objects.using(db_alias):
        if prize.startrun and prize.startrun.order:
            prize.prev_run = (
                SpeedRun.objects.using(db_alias).filter(
                    event=prize.startrun.event_id, order__lt=prize.startrun.order
                )
                .order_by('order')
                .last()
            )
            prize.next_run = (
                SpeedRun.objects.using(db_alias).filter(
                    event=prize.endrun.event_id, order__gt=prize.endrun.order
                )
                .order_by('order')
                .first()
            )
            prize.save()


def noop(a, b):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_add_prev_next_run_to_prize'),
    ]

    operations = [
        migrations.RunPython(populate_prev_next_run, noop, elidable=True)
    ]
