# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-05 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_populate_prev_next_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paypalimgurl',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Logo URL'),
        ),
    ]
