# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_add_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hashtag',
            field=models.CharField(blank=True, help_text='Normally you can use the short id for this, but this value can override it.', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='targetamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[tracker.validators.positive, tracker.validators.nonzero], verbose_name='Target Amount'),
        ),
    ]
