# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_add_prize_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='altimage',
            field=models.URLField(blank=True, default='', help_text=b'A second image to display in situations where the default image is not appropriate (tight spaces, stream, etc...)', max_length=1024, verbose_name=b'Alternate Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prize',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prize',
            name='extrainfo',
            field=models.TextField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.URLField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
    ]
