# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 21:30


from django.db import migrations


def remove_prize_nulls(apps, schema_editor):
    Prize = apps.get_model('tracker', 'Prize')  # noqa N806
    for field in ['altimage', 'description', 'extrainfo', 'image']:
        Prize.objects.filter(**{field: None}).update(**{field: ''})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_add_prize_key'),
    ]

    operations = [migrations.RunPython(remove_prize_nulls, noop, elidable=True)]
