# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-01 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_event_field_tweaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorcache',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache', to='tracker.Donor'),
        ),
    ]
