# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_prize_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='altimage',
            field=models.URLField(blank=True, help_text=b'A second image to display in situations where the default image is not appropriate (tight spaces, stream, etc...)', max_length=1024, verbose_name=b'Alternate Image'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='prize',
            name='extrainfo',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
