# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_paypal_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_one_step_screening',
            field=models.BooleanField(default=True, help_text=b'Turn this off if you use the "Head Donations" flow', verbose_name=b'Use One-Step Screening'),
        ),
    ]
