# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_add_one_step_screening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='state',
            field=models.CharField(choices=[(b'PENDING', b'Pending'), (b'DENIED', b'Denied'), (b'HIDDEN', b'Hidden'), (b'OPENED', b'Opened'), (b'CLOSED', b'Closed')], db_index=True, default=b'OPENED', max_length=32),
        ),
    ]
