# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-20 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_add_one_step_screening'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ['event__datetime', 'starttime', 'name']},
        ),
        migrations.RemoveField(
            model_name='prize',
            name='endrun',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='startrun',
        ),
    ]
