# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-16 19:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_add_index_to_bid_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='option_max_length',
            field=models.PositiveSmallIntegerField(help_text=b'If allowuseroptions is set, this sets the maximum length of user-submitted bid suggestions', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)], verbose_name=b'Max length of user suggestions'),
        ),
    ]
