# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-14 16:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_add_speedrun_twitch_name'),
        ('tracker', '0015_add_allow_donations'),
    ]

    operations = [
    ]
