# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-23 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_merge_20190914_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='istarget',
            field=models.BooleanField(default=False, help_text="Set this if this bid is a 'target' for donations (bottom level choice or challenge)", verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='prizecontributoremailtemplate',
            field=models.ForeignKey(blank=True, default=None, help_text="Email template to use when responding to prize contributor's submission requests", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_prizecontributortemplates', to='post_office.EmailTemplate', verbose_name='Prize Contributor Accept/Deny Email Template'),
        ),
    ]
