# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-23 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_fix_missing_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='ticketdraw',
        ),
        migrations.DeleteModel(
            name='PrizeTicket',
        ),
    ]
