# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-30 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_remove_prize_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='name',
            field=models.CharField(error_messages={'unique': 'Runner with this case-insensitive Name already exists.'}, max_length=64, unique=True),
        ),
    ]
