# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_remove_prize_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='platform',
            field=models.CharField(choices=[('TWITCH', 'Twitch'), ('MIXER', 'Mixer'), ('FACEBOOK', 'Facebook'), ('YOUTUBE', 'Youtube')], default='TWITCH', max_length=20),
        ),
        migrations.AlterField(
            model_name='bid',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
