# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 07:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_add_paypal_logo_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hashtag',
            field=models.CharField(default='', help_text='Normally you can use the short id for this, but this value can override it.', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='short',
            field=models.CharField(help_text='This must be unique, as it is used for slugs.', max_length=64, unique=True, validators=[django.core.validators.validate_slug]),
        ),
    ]
