# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-28 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tracker.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_add_event_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='addresscountry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=tracker.models.fields.OneToOneOrNoneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='prizecontributoremailtemplate',
            field=models.ForeignKey(blank=True, default=None, help_text="Email template to use when responding to prize contributor's submission requests", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_prizecontributortemplates', to='post_office.EmailTemplate', verbose_name='Prize Contributor Accept/Deny Email Template'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prizecoordinator',
            field=models.ForeignKey(blank=True, default=None, help_text='The person responsible for managing prize acceptance/distribution', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Prize Coordinator'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prizeshippedemailtemplate',
            field=models.ForeignKey(blank=True, default=None, help_text='Email template to use when the a prize has been shipped to its recipient).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_prizeshippedtemplates', to='post_office.EmailTemplate', verbose_name='Prize Shipped Email Template'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prizewinneracceptemailtemplate',
            field=models.ForeignKey(blank=True, default=None, help_text='Email template to use when someone accepts a prize (and thus it needs to be shipped).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_prizewinneraccepttemplates', to='post_office.EmailTemplate', verbose_name='Prize Accepted Email Template'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prizewinneremailtemplate',
            field=models.ForeignKey(blank=True, default=None, help_text='Email template to use when someone wins a prize.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_prizewinnertemplates', to='post_office.EmailTemplate', verbose_name='Prize Winner Email Template'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prize',
            name='handler',
            field=models.ForeignKey(help_text='User account responsible for prize shipping', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='runner',
            name='donor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Donor'),
        ),
    ]
