# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 23:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_add_moderation_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedrun',
            name='runners',
            field=models.ManyToManyField(to='tracker.Runner'),
        ),
    ]
