# Generated by Django 2.2.16 on 2020-09-17 21:48

from django.db import migrations, models
import django.db.models.deletion
import tracker.models.fields
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_donor_cache_tweaks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interstitial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[tracker.validators.positive, tracker.validators.nonzero])),
                ('suborder', models.IntegerField(validators=[tracker.validators.positive, tracker.validators.nonzero])),
                ('length', tracker.models.fields.TimestampField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.Event')),
            ],
            options={
                'ordering': ('event', 'order', 'suborder'),
                'unique_together': {('event', 'order', 'suborder')},
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interstitial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.Interstitial')),
                ('interviewers', models.CharField(max_length=128)),
                ('subjects', models.CharField(max_length=128)),
                ('topic', models.CharField(max_length=128)),
                ('producer', models.CharField(blank=True, max_length=128)),
                ('camera_operator', models.CharField(blank=True, max_length=128)),
                ('social_media', models.BooleanField()),
                ('clips', models.BooleanField()),
            ],
            options={
                'permissions': (('view_interviews', 'Can view interviews'),),
            },
            bases=('tracker.interstitial',),
        ),
        migrations.CreateModel(
            name='HostSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('end_run', models.ForeignKey(help_text='The last run this host slot covers', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.SpeedRun')),
                ('start_run', models.ForeignKey(help_text='The first run this host slot covers', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.SpeedRun')),
            ],
            options={
                'ordering': ('start_run',),
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('interstitial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.Interstitial')),
                ('sponsor_name', models.CharField(max_length=64)),
                ('ad_name', models.CharField(max_length=64)),
                ('ad_type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image')], max_length=8)),
                ('filename', models.CharField(max_length=64)),
            ],
            options={
                'permissions': (('view_ads', 'Can view ads'),),
                'unique_together': {('sponsor_name', 'ad_name')},
            },
            bases=('tracker.interstitial',),
        ),
    ]
