# Generated by Django 2.2.16 on 2020-09-23 23:03

import logging
import os

from django.core import serializers
from django.db import migrations

logger = logging.getLogger(__name__)

def load_countries(apps, schema_editor):
    # This is IMPORTANT, make sure it gets moved the next time you squash migrations
    Country = apps.get_model('tracker', 'Country')
    count = 0
    path = os.path.normpath(os.path.join(os.path.dirname(__file__), '../fixtures/countries.json'))
    with open(path) as data:
        for country in serializers.deserialize('json', data.read()):
            created = Country.objects.get_or_create(alpha2=country.object.alpha2, defaults=dict(
                name=country.object.name,
                alpha3=country.object.alpha3,
                numeric=country.object.numeric,
            ))[1]
            if created:
                count +=1
    logger.info(f'Loaded {count} fixture(s) for country')

def no_op(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_donor_cache_tweaks'),
    ]

    operations = [
        migrations.RunPython(load_countries, no_op)
    ]
