# Generated by Django 2.2.16 on 2020-09-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_donor_cache_tweaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='requestedalias',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Requested Alias'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='requestedemail',
            field=models.EmailField(blank=True, default='', max_length=128, verbose_name='Requested Contact Email'),
        ),
    ]
