# Generated by Django 2.2.16 on 2020-09-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_add_interstitials_and_hosts'),
        ('tracker', '0009_load_countries'),
    ]

    operations = [
    ]
