# Generated by Django 2.2.16 on 2020-09-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_load_countries'),
        ('tracker', '0009_add_interstitials_and_hosts'),
        ('tracker', '0011_backfill_alias'),
    ]

    operations = [
    ]
