# Generated by Django 2.2.16 on 2020-10-09 00:20

from django.db import migrations


def remove_donation_nulls(apps, schema_editor):
    Donation = apps.get_model('tracker', 'Donation')
    for field in ['requestedalias', 'requestedemail']:
        Donation.objects.filter(**{field: None}).update(**{field: ''})


def noop(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_donor_cache_tweaks'),
    ]

    operations = [
        migrations.RunPython(remove_donation_nulls, noop, elidable=True)
    ]
