# Generated by Django 2.2.16 on 2020-09-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_merge_20200926_1759'),
        ('tracker', '0012_merge_20200928_1510'),
    ]

    operations = [
    ]
