# Generated by Django 2.2.16 on 2020-10-09 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_zz_remove_donation_nulls'), # named as such as a horrible hack to ensure it runs first, very much relies on Django internal behavior and might break in the future
        ('tracker', '0013_merge_20200928_1548'),
    ]

    operations = [
    ]
