# Generated by Django 2.2.16 on 2020-10-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_add_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prize_drawing_date',
            field=models.DateField(blank=True, help_text='Prizes will be eligible for drawing on or after this date, otherwise they will be eligible for drawing immediately after their window closes.', null=True, verbose_name='Prize Drawing Date'),
        ),
    ]
