# Generated by Django 2.2.16 on 2021-01-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_add_prize_drawing_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['event__datetime', 'speedrun__starttime', 'parent__name', 'name'], 'permissions': (('top_level_bid', 'Can create new top level bids'), ('delete_all_bids', 'Can delete bids with donations attached'), ('view_hidden_bid', 'Can view hidden bids'))},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'get_latest_by': 'timereceived', 'ordering': ['-timereceived'], 'permissions': (
            ('delete_all_donations', 'Can delete non-local donations'),
            ('view_full_list', 'Can view full donation list'), ('view_comments', 'Can view all comments'),
            ('view_pending_donation', 'Can view pending donations'), ('view_test', 'Can view test donations'),
            ('send_to_reader', 'Can send donations to the reader'))},
        ),
    ]
