# Generated by Django 2.2.16 on 2020-10-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_migrate_paypal_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='paypalemail',
        ),
        migrations.RemoveField(
            model_name='event',
            name='paypalcurrency',
        ),
        migrations.RemoveField(
            model_name='event',
            name='paypalemail',
        ),
        migrations.RemoveField(
            model_name='event',
            name='paypalimgurl',
        ),
    ]
