# Generated by Django 2.2.16 on 2021-01-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_add_blurb_to_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
