# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-30 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_add_uniqueness_message_runner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='platform',
            field=models.CharField(choices=[('TWITCH', 'Twitch'), ('MIXER', 'Mixer'), ('FACEBOOK', 'Facebook'),
                                            ('YOUTUBE', 'Youtube')], default='TWITCH', help_text='Streaming Platforms', max_length=20),
        ),
        migrations.AddField(
            model_name='runner',
            name='pronouns',
            field=models.CharField(blank=True, help_text='They/Them', max_length=20),
        ),
    ]
