# Generated by Django 2.2.19 on 2021-06-22 05:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_add_pinned_to_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[tracker.validators.positive, tracker.validators.nonzero])),
                ('name', models.CharField(max_length=64)),
                ('visible', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('short_description', models.TextField(blank=True, help_text='Alternative description text to display in tight spaces', max_length=256, verbose_name='Short Description')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Event')),
            ],
            options={
                'ordering': ('event', 'amount'),
                'unique_together': {('event', 'amount')},
            },
        ),
    ]
