# Generated by Django 2.2.20 on 2021-08-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_add_pinned_to_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='paypalcurrency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('CAD', 'Canadian Dollars'), ('JPY', 'Japanese Yens')], default='USD', max_length=8, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('CAD', 'Canadian Dollars'), ('JPY', 'Japanese Yens')], max_length=8, verbose_name='Currency'),
        ),
    ]
