# Generated by Django 2.2.19 on 2021-06-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_add_milestone'),
        ('tracker', '0020_add_pinned_to_bid'),
    ]

    operations = [
    ]
