# Generated by Django 3.2.15 on 2022-12-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_merge_20210628_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'datetime', 'ordering': ('-datetime',), 'permissions': (('can_edit_locked_events', 'Can edit locked events'),)},
        ),
    ]
