# Generated by Django 2.2.20 on 2021-12-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_add_milestone'),
        ('tracker', '0021_alter_currency_choices'),
    ]

    operations = [
    ]
