# Generated by Django 2.2.20 on 2021-12-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_merge_20211215_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='receivertype',
            field=models.CharField(choices=[('default', 'Default'), ('msf2021', '国境なき医師団')], default='default', max_length=16, verbose_name='Receiver Type'),
        ),
    ]
