# Generated by Django 3.2.15 on 2022-12-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_reverse_event_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'datetime', 'ordering': ('-datetime',), 'permissions': (('can_edit_locked_events', 'Can edit locked events'),)},
        ),
        migrations.AddField(
            model_name='speedrun',
            name='onsite',
            field=models.CharField(choices=[('ONSITE', 'Onsite'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=6),
        ),
    ]
