# Generated by Django 2.2.20 on 2021-12-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_event_receivertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='receivernotice',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Receiver Notice Message'),
        ),
    ]
