# Generated by Django 3.2.15 on 2023-01-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_add_onsite_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='repeat',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True,
                                      help_text='Informational field for repeated challenges, must be a divisor of goal'),
        ),
    ]
