# Generated by Django 4.1.5 on 2023-02-20 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_event_receiver_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedrun',
            name='commentators',
        ),
        migrations.CreateModel(
            name='Headset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pronouns', models.CharField(blank=True, help_text='They/Them', max_length=20)),
                ('runner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.runner')),
            ],
        ),
        migrations.AddField(
            model_name='speedrun',
            name='hosts',
            field=models.ManyToManyField(related_name='hosting_for', to='tracker.headset'),
        ),
        migrations.AddField(
            model_name='speedrun',
            name='commentators',
            field=models.ManyToManyField(related_name='commentating_for', to='tracker.headset'),
        ),
    ]
