# Generated by Django 2.2.20 on 2022-08-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_add_socials_to_runner'),
        ('tracker', '0021_merge_20210628_2126'),
    ]

    operations = [
    ]
