# Generated by Django 4.1.5 on 2023-04-03 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_migrate_hosts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostSlot',
        ),
    ]
