# Generated by Django 4.1.5 on 2023-04-17 03:22

from django.db import migrations

def merge_case(apps, schema_editor):
    Headset = apps.get_model('tracker', 'Headset')

    slots = {}

    all_slots = list(Headset.objects.order_by('id'))

    used_slots = set()

    for slot in all_slots:
        if slot.id in used_slots:
            continue
        slots[slot.id] = [s.id for s in Headset.objects.filter(name__iexact=slot.name).exclude(pk=slot.pk)]
        used_slots |= set(slots[slot.id])

    for squash, others in slots.items():
        squash = Headset.objects.get(pk=squash)
        for other in others:
            other = Headset.objects.get(pk=other)
            for run in other.hosting_for.all():
                run.hosts.add(squash)
            for run in other.commentating_for.all():
                run.commentators.add(squash)
            other.delete()


def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_delete_host_slots'),
    ]

    operations = [
        migrations.RunPython(merge_case, noop)
    ]
