# Generated by Django 4.1.6 on 2023-04-29 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tracker.models.donation


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0029_headset_merge_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationProcessAction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'from_state',
                    models.CharField(
                        choices=[
                            (
                                tracker.models.donation.DonationProcessState[
                                    'UNPROCESSED'
                                ],
                                'No processing has happened on the donation yet',
                            ),
                            (
                                tracker.models.donation.DonationProcessState['FLAGGED'],
                                'The donation has been flagged for head donations to process',
                            ),
                            (
                                tracker.models.donation.DonationProcessState['READY'],
                                'The donation is ready for the reader to process',
                            ),
                            (
                                tracker.models.donation.DonationProcessState['READ'],
                                'The donation comment was read by the reader',
                            ),
                            (
                                tracker.models.donation.DonationProcessState['IGNORED'],
                                'The donation comment was ignored by the reader',
                            ),
                            (
                                tracker.models.donation.DonationProcessState[
                                    'APPROVED'
                                ],
                                'The donation was approved but not sent for reading',
                            ),
                            (
                                tracker.models.donation.DonationProcessState['DENIED'],
                                'The donation comment was rejected',
                            ),
                            (
                                tracker.models.donation.DonationProcessState['UNKNOWN'],
                                'The donation is in an unknown or corrupted processing state',
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'to_state',
                    models.CharField(
                        choices=[
                            (
                                tracker.models.donation.DonationProcessState[
                                    'UNPROCESSED'
                                ],
                                'No processing has happened on the donation yet',
                            ),
                            (
                                tracker.models.donation.DonationProcessState['FLAGGED'],
                                'The donation has been flagged for head donations to process',
                            ),
                            (
                                tracker.models.donation.DonationProcessState['READY'],
                                'The donation is ready for the reader to process',
                            ),
                            (
                                tracker.models.donation.DonationProcessState['READ'],
                                'The donation comment was read by the reader',
                            ),
                            (
                                tracker.models.donation.DonationProcessState['IGNORED'],
                                'The donation comment was ignored by the reader',
                            ),
                            (
                                tracker.models.donation.DonationProcessState[
                                    'APPROVED'
                                ],
                                'The donation was approved but not sent for reading',
                            ),
                            (
                                tracker.models.donation.DonationProcessState['DENIED'],
                                'The donation comment was rejected',
                            ),
                            (
                                tracker.models.donation.DonationProcessState['UNKNOWN'],
                                'The donation is in an unknown or corrupted processing state',
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'occurred_at',
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    'actor',
                    models.ForeignKey(
                        blank=True,
                        help_text='Who performed the processing action',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'donation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='tracker.donation',
                    ),
                ),
                (
                    'originating_action',
                    models.ForeignKey(
                        help_text='Original action that this action is undoing/modifying/etc.',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='tracker.donationprocessaction',
                    ),
                ),
            ],
            options={
                'permissions': (
                    (
                        'delete_all_process_actions',
                        'Can delete donation processing action history',
                    ),
                    (
                        'view_all_donation_actions',
                        'Can view donation processing actions performed by any user',
                    ),
                ),
            },
        ),
    ]
