# Generated by Django 4.2 on 2023-04-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_headset_merge_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='chain',
            field=models.BooleanField(default=False, help_text='Use for stretch goals, this requires a linear chain of single-descendants to work'),
        ),
        migrations.AddField(
            model_name='bid',
            name='chain_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, help_text='The total goal of all remaining bids in the chain (EXCLUDING this bid)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='chain_goal',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, help_text='The total goal of all preceding bids in the chain (INCLUDING this bid)', max_digits=20, null=True),
        ),
    ]
