# Generated by Django 4.2 on 2023-05-13 20:38

from django.db import migrations, models
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_add_bid_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorcache',
            name='donation_avg',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='donorcache',
            name='donation_count',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='donorcache',
            name='donation_max',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='donorcache',
            name='donation_total',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, editable=False, max_digits=20),
        ),
    ]
