# Generated by Django 3.2.20 on 2023-08-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_add_euros_to_donation_and_event'),
        ('tracker', '0032_add_more_indices'),
    ]

    operations = [
    ]
