# Generated by Django 4.2 on 2023-11-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_add_more_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedrun',
            name='layout',
            field=models.CharField(blank=True, help_text='Which OBS layout to use', max_length=64),
        ),
    ]
