# Generated by Django 4.2 on 2023-12-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_add_anchor_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={},
        ),
        migrations.AddField(
            model_name='interview',
            name='prerecorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='clips',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='social_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='subjects',
            field=models.CharField(blank=True, help_text='i.e. interviewees', max_length=128),
        ),
        migrations.AlterField(
            model_name='interview',
            name='topic',
            field=models.CharField(help_text='what the interview is about', max_length=128),
        ),
    ]
