# Generated by Django 4.2 on 2024-01-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_interview_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.videolinktype')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_links', to='tracker.speedrun')),
            ],
            options={
                'unique_together': {('run', 'link_type')},
            },
        ),
    ]
