# Generated by Django 5.0 on 2024-02-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_add_milestone_start'),
        ('tracker', '0037_add_incentive_timing'),
    ]

    operations = [
    ]
