# Generated by Django 4.2 on 2024-01-18 06:23

from django.db import migrations, models
import tracker.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_add_video_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='close_at',
            field=models.CharField(blank=True, help_text='approximately how far into the run the incentive will need to be closed', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='estimate',
            field=tracker.models.fields.TimestampField(blank=True, help_text='how much this incentive will add to run/setup time, if applicable', null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='post_run',
            field=models.BooleanField(default=False, help_text='this incentive takes place after the run (part of setup time)'),
        ),
    ]
