# Generated by Django 5.0 on 2024-02-21 20:49

import tracker.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_add_video_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='start',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[tracker.validators.positive]),
        ),
    ]
