# Generated by Django 3.2.20 on 2024-04-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_merge_20230814_1327'),
        ('tracker', '0038_milestone_start_zero'),
    ]

    operations = [
    ]
