# Generated by Django 5.0 on 2024-02-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_merge_20240213_2207'),
        ('tracker', '0038_milestone_start_zero'),
    ]

    operations = [
    ]
