# Generated by Django 3.2.20 on 2024-07-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_add_incentive_timing'),
        ('tracker', '0039_merge_20240413_0642'),
    ]

    operations = [
    ]
