# Generated by Django 5.0 on 2024-06-27 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_add_incentive_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunTag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        error_messages={
                            'unique': 'Tags must be case-insensitively unique.'
                        },
                        max_length=32,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='speedrun',
            name='priority_tag',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='priority_runs',
                to='tracker.runtag',
            ),
        ),
        migrations.AddField(
            model_name='speedrun',
            name='tags',
            field=models.ManyToManyField(
                blank=True, related_name='runs', to='tracker.runtag'
            ),
        ),
    ]
