# Generated by Django 5.0 on 2024-06-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_add_interstitial_anchor'),
        ('tracker', '0040_add_run_tags'),
    ]

    operations = []
