# Generated by Django 3.2.20 on 2024-08-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0040_add_interstitial_anchor'),
        ('tracker', '0040_merge_20240729_1306'),
    ]

    operations = [
    ]
