# Generated by Django 5.1 on 2024-08-30 19:13

from django.db import migrations


def can_search_forwards(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.filter(app_label='tracker', model='userprofile').first()
    if ct is None:
        return  # initial migration?
    old = Permission.objects.filter(content_type=ct, codename='can_search').first()
    if old is None:
        raise Exception('Could not find old permission')
    new = Permission.objects.get_or_create(content_type=ct, name='Can use User lookup endpoint', codename='can_search_for_user')[0]
    new.user_set.add(*old.user_set.all())
    new.group_set.add(*old.group_set.all())
    old.delete()


def can_search_backwards(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.get(app_label='tracker', model='userprofile')
    new = Permission.objects.filter(content_type=ct, codename='can_search_for_user').first()
    if new is None:
        raise Exception('Could not find new permission')
    old = Permission.objects.get_or_create(content_type=ct, name='Can use search url', codename='can_search')[0]
    old.user_set.add(*new.user_set.all())
    old.group_set.add(*new.group_set.all())
    new.delete()


def view_full_names_forwards(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.filter(app_label='tracker', model='donor').first()
    if ct is None:
        return  # initial migration?
    old = Permission.objects.filter(content_type=ct, codename='view_usernames').first()
    if old is None:
        raise Exception('Could not find old permission')
    new = Permission.objects.get_or_create(content_type=ct, name='Can search for donors by full name', codename='view_full_names')[0]
    new.user_set.add(*old.user_set.all())
    new.group_set.add(*old.group_set.all())
    old.delete()
    Permission.objects.filter(codename='view_emails').update(name='Can search for donors by email address')


def view_full_names_backwards(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.get(app_label='tracker', model='donor')
    new = Permission.objects.filter(content_type=ct, codename='view_full_names').first()
    if new is None:
        raise Exception('Could not find new permission')
    old = Permission.objects.get_or_create(content_type=ct, name='Can view full usernames', codename='view_usernames')[0]
    old.user_set.add(*new.user_set.all())
    old.group_set.add(*new.group_set.all())
    new.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
        ('tracker', '0041_permissions_pass'),
    ]

    operations = [
        migrations.RunPython(can_search_forwards, can_search_backwards, elidable=True),
        migrations.RunPython(view_full_names_forwards, view_full_names_backwards, elidable=True),
    ]
