# Generated by Django 5.1 on 2024-09-18 20:56

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_search_permissions_rename'),
    ]

    # after wrestling a bit this was the best way to avoid the conflict on the spike branch, can be removed later

    replaces = [
        ('tracker', '0040_add_run_tags'),
        ('tracker', '0042_add_interstitial_tags'),
        ('tracker', '0044_rename_model_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        error_messages={
                            'unique': 'Tags must be case-insensitively unique.'
                        },
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile('^[-a-zA-Z0-9_]+\\Z'),
                                'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.',
                                'invalid',
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='interstitial',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='interstitials', to='tracker.tag'),
        ),
        migrations.AddField(
            model_name='prize',
            name='tags',
            field=models.ManyToManyField(
                blank=True, related_name='prizes', to='tracker.tag'
            ),
        ),
        migrations.AddField(
            model_name='speedrun',
            name='priority_tag',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='priority_runs',
                to='tracker.tag',
            ),
        ),
        migrations.AddField(
            model_name='speedrun',
            name='tags',
            field=models.ManyToManyField(
                blank=True, related_name='runs', to='tracker.tag'
            ),
        ),
    ]
