# Generated by Django 5.1 on 2024-09-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_add_interstitial_tags'),
        ('tracker', '0042_search_permissions_rename'),
    ]

    operations = []
