# Generated by Django 5.1 on 2024-09-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_add_interstitial_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RunTag',
            new_name='Tag',
        ),
        migrations.AddField(
            model_name='prize',
            name='tags',
            field=models.ManyToManyField(
                blank=True, related_name='prizes', to='tracker.tag'
            ),
        ),
    ]
