# Generated by Django 5.1 on 2024-09-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0043_merge_20240916_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RunTag',
            new_name='Tag',
        ),
    ]
