# Generated by Django 5.1.2 on 2024-10-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_merge_20240829_1326'),
        ('tracker', '0047_merge_talent_contenttypes'),
    ]

    operations = [
    ]
