# Generated by Django 5.1 on 2024-10-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0047_merge_talent_contenttypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={},
        ),
    ]
