# Generated by Django 5.1.2 on 2024-12-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0048_merge_20241014_0900'),
        ('tracker', '0048_remove_old_ad_permission'),
    ]

    operations = [
    ]
