# Generated by Django 5.1.4 on 2025-01-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0048_remove_old_ad_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='run',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.speedrun'),
        ),
    ]
