# Generated by Django 5.1.4 on 2025-01-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0049_add_milestone_run'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='interviewers',
            new_name='interviewers_text',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='subjects',
            new_name='subjects_text',
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(related_name='interviewer_for', to='tracker.talent'),
        ),
        migrations.AddField(
            model_name='interview',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='i.e. interviewees', related_name='subject_for',
                                         to='tracker.talent'),
        ),
    ]
