# Generated by Django 5.1.4 on 2025-01-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0049_add_milestone_run'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['event__datetime', 'speedrun__starttime', 'parent__name', 'name'], 'permissions': (('top_level_bid', 'Can create new top level bids'), ('delete_all_bids', 'Can delete bids with donations attached'), ('approve_bid', 'Can approve/deny pending bids'), ('view_hidden_bid', 'Can view hidden bids'))},
        ),
    ]
