# Generated by Django 5.1.4 on 2025-01-09 22:36

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0049_add_milestone_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolinktype',
            name='name',
            field=models.CharField(error_messages={'unique': 'Tags must be case-insensitively unique.'}, max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
