# Generated by Django 5.1.4 on 2025-01-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0051_migrate_interview_talent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interviewers_text',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='subjects_text',
        ),
    ]
