# Generated by Django 5.1.4 on 2025-01-18 00:33

from django.db import migrations


def target_to_milestone(apps, schema_editor):
    Event = apps.get_model('tracker', 'Event')
    Milestone = apps.get_model('tracker', 'Milestone')
    for e in Event.objects.all():
        if e.targetamount:
            Milestone.objects.get_or_create(event=e, amount=e.targetamount, defaults={'name': 'Target', 'visible': True})


def noop(apps, schema_editor):
    # no sensible way to undo this, so just leave it alone
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0052_delete_interview_text_columns'),
    ]

    operations = [
        migrations.RunPython(target_to_milestone, noop, elidable=True)
    ]
