# Generated by Django 5.1.4 on 2025-01-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0053_migrate_target_to_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='targetamount',
        ),
    ]
