# Generated by Django 5.1.2 on 2025-01-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0049_merge_20241215_1449'),
        ('tracker', '0054_delete_event_targetamount'),
    ]

    operations = [
    ]
