# Generated by Django 5.1.4 on 2025-01-21 01:16

from django.db import migrations
from django.db.models import Q, F


def backfill_ipns(apps, schema_editor):
    IPN = apps.get_model('ipn', 'PayPalIPN')
    Donation = apps.get_model('tracker', 'Donation')
    Donation.objects.exclude(domain='PAYPAL').update(cleared_at=F('timereceived'))
    for i in IPN.objects.order_by('created_at'):
        f = Q(id=i.custom.split(':')[0]) if ':' in i.custom else Q(domainId=i.txn_id)
        if (d := Donation.objects.filter(f).first()):
            d.ipns.add(i)
            if i.payment_status in {'Completed', 'Canceled_Reversal'} and d.cleared_at is None:
                d.cleared_at = i.created_at
                d.save()
            elif i.payment_status in {'Refunded', 'Reversed'}:
                d.cleared_at = None
                d.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0055_add_donation_ipns'),
    ]

    operations = [
        migrations.RunPython(backfill_ipns, noop, elidable=True)
    ]
