# Generated by Django 5.1.4 on 2025-01-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0056_backfill_donation_ipns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedrun',
            name='category',
            field=models.CharField(default='', blank=True, help_text='The type of run being performed', max_length=64),
            preserve_default=False,
        ),
    ]
