# Generated by Django 5.1.4 on 2025-01-23 22:17
from django.core.management import CommandError
from django.db import migrations


def check_for_deprecated_runners(apps, schema_editor):
    problems = []
    for r in apps.get_model('tracker', 'SpeedRun').objects.exclude(deprecated_runners='').select_related('event').prefetch_related('runners'):
        actual = ', '.join(sorted(set(r.lower() for r in r.deprecated_runners.split(', '))))
        expected = ', '.join(sorted(t.name.lower() for t in r.runners.all()))
        if actual != expected:
            problems.append((r.event.short, r.id, r.name, expected, actual))
    if problems:
        problems = '\n'.join(str(p) for p in problems)
        raise CommandError(f"""----------
The following runs had mismatched runner entries, please validate/fix before migrating as data loss might result otherwise
This can also happen if a Talent entry had its name changed
----------
{('event_short', 'id', 'name', 'expected', 'actual')}
{problems}
----------""")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0057_remove_category_nulls'),
    ]

    operations = [
        migrations.RunPython(check_for_deprecated_runners, noop, elidable=True),
        migrations.RemoveField(
            model_name='speedrun',
            name='deprecated_runners',
        ),
    ]
