# Generated by Django 5.1.2 on 2025-01-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_add_euros_to_donation_and_event'),
        ('tracker', '0058_remove_deprecated_runners'),
    ]

    operations = [
    ]
