# Generated by Django 5.1.4 on 2025-01-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0060_add_bid_approval_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='accepted_number',
            field=models.IntegerField(blank=True, verbose_name='Accepted Number of Options', help_text='Number of accepted options that will be used, e.g. top two choices for a race', null=True),
        ),
    ]
