# Generated by Django 5.1.4 on 2025-01-31 21:32

from django.db import migrations


def backfill_accepted_number(apps, schema_editor):
    Bid = apps.get_model('tracker', 'bid')
    Bid.objects.filter(istarget=False, parent=None, accepted_number=None).update(accepted_number=1)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0061_add_bid_accepted_number'),
    ]

    operations = [
        migrations.RunPython(backfill_accepted_number, noop, elidable=True)
    ]
