# Generated by Django 5.1.4 on 2025-02-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0062_backfill_accepted_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='receiver_logo',
            field=models.URLField(blank=True, help_text='URL to display a logo image for the receiver', max_length=256),
        ),
        migrations.AddField(
            model_name='event',
            name='receiver_privacy_policy',
            field=models.URLField(blank=True, help_text='URL to link to an external privacy policy specific to the receiver', max_length=256),
        ),
        migrations.AddField(
            model_name='event',
            name='receiver_solicitation_text',
            field=models.CharField(blank=True, help_text='Override the standard messaging on the receive emails checkbox', max_length=128),
        ),
    ]
