# Generated by Django 5.1.4 on 2025-02-26 19:28

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0063_add_receiver_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Tags must be case-insensitively unique.'}, max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='groups',
            field=models.ManyToManyField(blank=True, to='tracker.donationgroup'),
        ),
    ]
