# Generated by Django 4.2.17 on 2025-02-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0063_add_receiver_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='pinned',
        ),
    ]
