# Generated by Django 5.1.6 on 2025-03-09 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0064_add_donation_groups'),
        ('tracker', '0064_remove_bid_pinned'),
    ]

    operations = [
    ]
