# Generated by Django 5.2 on 2025-05-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0065_add_donation_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='locked',
            new_name='archived',
        ),
        migrations.AlterField(
            model_name='event',
            name='allow_donations',
            field=models.BooleanField(
                default=True,
                help_text='Whether or not donations are open for this event. Archiving an event will clear this flag.',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='archived',
            field=models.BooleanField(
                default=False,
                help_text='Event cannot be edited. Users with permission to edit events can unarchive at any time.',
            ),
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'datetime', 'ordering': ('-datetime',)},
        ),
    ]
