# Generated by Django 5.2 on 2025-05-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0066_rename_locked_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='draft',
            field=models.BooleanField(
                default=False,
                help_text='Event is in a draft state. The event itself will be publicly viewable, but none of the models relating to it will be, and no donations can be made.',
            ),
        ),
    ]
