# Generated by Django 5.2 on 2025-05-26 17:21

import tracker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0067_add_event_draft_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='locale_code',
            field=models.CharField(
                blank=True,
                help_text='Overrides the global LANGUAGE_CODE setting specifically for this event.',
                max_length=16,
                validators=[tracker.validators.validate_locale],
            ),
        ),
    ]
