# Generated by Django 5.2 on 2025-05-26 17:43
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0068_add_event_locale_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorcache',
            name='donation_med',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=20,
                editable=False,
                default=0,
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name='donorcache',
            name='currency',
            field=models.CharField(max_length=16, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorcache',
            name='donor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cache',
                to='tracker.donor',
            ),
        ),
        migrations.AlterModelOptions(
            name='donorcache',
            options={'ordering': ('donor',), 'verbose_name': 'Donor Total'},
        ),
    ]
