# Generated by Django 5.2 on 2025-05-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0068_add_event_maximum_paypal_amount'),
        ('tracker', '0070_backfill_donor_cache_enhancements'),
    ]

    operations = []
