# Generated by Django 5.2 on 2025-06-11 01:08

from django.db import migrations, models
import django.db.models.deletion

import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0070_backfill_donor_cache_enhancements'),
    ]

    operations = [
        migrations.RenameModel('PrizeWinner', 'PrizeClaim'),
        migrations.RenameField('PrizeClaim', 'emailsent', 'winneremailsent'),
        migrations.RenameField('PrizeKey', 'prize_winner', 'prize_claim'),
        migrations.RemoveField('PrizeClaim', 'sumcount'),
        migrations.AlterField(
            model_name='prizeclaim',
            name='prize',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='claims',
                to='tracker.prize',
            ),
        ),
        migrations.AlterModelOptions(
            name='prizeclaim',
            options={'verbose_name': 'Prize Claim'},
        ),
        migrations.AlterField(
            model_name='prizekey',
            name='prize',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='prize_keys',
                to='tracker.prize',
            ),
        ),
        migrations.AlterField(
            model_name='prizekey',
            name='prize_claim',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='prize_key',
                to='tracker.prizeclaim',
            ),
        ),
        migrations.AlterField(
            model_name='donorprizeentry',
            name='weight',
            field=models.DecimalField(
                decimal_places=2,
                default=None,
                null=True,
                editable=False,
                help_text='DEPRECATED - do not use',
                max_digits=20,
                validators=[tracker.validators.positive, tracker.validators.nonzero],
                verbose_name='Entry Weight',
            ),
        ),
        migrations.AlterField(
            model_name='prize',
            name='maximumbid',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                editable=False,
                max_digits=20,
                null=True,
                validators=[tracker.validators.positive, tracker.validators.nonzero],
                verbose_name='DEPRECATED - do not use',
            ),
        ),
        migrations.AlterField(
            model_name='prizeclaim',
            name='winner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='prizeclaims',
                to='tracker.donor',
            ),
        ),
        migrations.AlterField(
            model_name='prizeclaim',
            name='winneremailsent',
            field=models.BooleanField(
                default=False, verbose_name='Winner Notification Email Sent'
            ),
        ),
        migrations.AlterField(
            model_name='prize',
            name='maxmultiwin',
            field=models.IntegerField(
                default=1,
                editable=False,
                validators=[tracker.validators.positive, tracker.validators.nonzero],
                verbose_name='Max Wins per Donor',
            ),
        ),
        migrations.AlterField(
            model_name='prizeclaim',
            name='shippingstate',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('SHIPPED', 'Shipped'),
                    ('AWARDED', 'Awarded'),
                    ('N/A', 'N/A'),
                ],
                default='PENDING',
                max_length=64,
                verbose_name='Shipping State',
            ),
        ),
    ]
