# Generated by Django 5.2 on 2025-04-30 22:43

import tracker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0070_backfill_donor_cache_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maximum_paypal_donation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enforces a maximum donation amount on the PayPal donation page. Uses the global setting if left blank.', max_digits=20, null=True, validators=[tracker.validators.positive, tracker.validators.nonzero], verbose_name='Maximum PayPal Donation'),
        ),
    ]
