# Generated by Django 5.2 on 2025-06-11 01:54

from django.db import migrations


def prize_claim_forwards(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    old_perms = Permission.objects.filter(codename__endswith='_prizewinner')
    for perm in old_perms:
        new_perm = Permission.objects.get_or_create(content_type=perm.content_type, codename=perm.codename.replace('_prizewinner', '_prizeclaim'))[0]
        new_perm.user_set.add(*perm.user_set.all())
        new_perm.group_set.add(*perm.group_set.all())
    old_perms.delete()


def prize_claim_backwards(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    old_perms = Permission.objects.filter(codename__endswith='_prizeclaim')
    for perm in old_perms:
        new_perm = Permission.objects.get_or_create(content_type=perm.content_type, codename=perm.codename.replace('_prizeclaim', '_prizewinner'))[0]
        new_perm.user_set.add(*perm.user_set.all())
        new_perm.group_set.add(*perm.group_set.all())
    old_perms.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
        ('tracker', '0071_rename_prize_winner'),
    ]

    operations = [
        migrations.RunPython(prize_claim_forwards, prize_claim_backwards, elidable=True),
    ]
