# Generated by Django 5.2 on 2025-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0071_add_event_maximum_paypal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='screening_mode',
            field=models.CharField(
                max_length=16,
                choices=[
                    ('host_only', 'Host Only'),
                    ('one_pass', 'One Pass'),
                    ('two_pass', 'Two Pass'),
                ],
                default='one_pass',
                help_text='See the README for more details.',
            ),
        ),
    ]
