# Generated by Django 5.2 on 2025-06-02 17:22

from django.db import migrations


def forwards(apps, schema_editor):
    Event = apps.get_model('tracker', 'Event')
    Event.objects.filter(use_one_step_screening=False).update(screening_mode='two_pass')


def backwards(apps, schema_editor):
    Event = apps.get_model('tracker', 'Event')
    Event.objects.filter(screening_mode='two_pass').update(use_one_step_screening=False)
    Event.objects.exclude(screening_mode='two_pass').update(use_one_step_screening=True)


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0072_add_event_screening_mode'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards, elidable=True),
    ]
