# Generated by Django 5.2 on 2025-06-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0073_migrate_screening_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='use_one_step_screening',
        ),
    ]
