# Generated by Django 5.2.3 on 2025-06-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0072_rename_prize_claim_permissions'),
        ('tracker', '0074_remove_event_one_step_screening'),
    ]

    operations = []
