# Generated by Django 5.2.3 on 2025-06-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0075_merge_20250620_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name='Timestamp'
            ),
        ),
    ]
