# Generated by Django 5.2.3 on 2025-06-26 01:37

import tracker.models.prize
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0076_add_index_log_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='imagefile',
            field=models.FileField(
                blank=True,
                null=True,
                storage=tracker.models.prize.prefer_prize_storage,
                upload_to=tracker.models.prize.prize_path_id,
            ),
        ),
    ]
