# Generated by Django 5.2.3 on 2025-07-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0077_alter_prize_imagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='twitch_id',
            field=models.IntegerField(
                blank=True,
                help_text='The unique, stable numeric ID returned by the Twitch API',
                null=True,
                unique=True,
                verbose_name='Twitch User ID',
            ),
        ),
        migrations.AlterField(
            model_name='donation',
            name='domain',
            field=models.CharField(
                choices=[
                    ('LOCAL', 'Local'),
                    ('CHIPIN', 'ChipIn'),
                    ('PAYPAL', 'PayPal'),
                    ('TWITCH', 'Twitch'),
                ],
                default='LOCAL',
                max_length=255,
            ),
        ),
    ]
