# Generated by Django 5.2.3 on 2025-07-04 21:08

from django.db import migrations
from django.db.models import F


def clear_prize_maximumbid(apps, schema_editor):
    Prize = apps.get_model('tracker', 'Prize')
    Prize.objects.filter(maximumbid=F('minimumbid')).update(maximumbid=None)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0077_alter_prize_imagefile'),
    ]

    operations = [migrations.RunPython(clear_prize_maximumbid, noop, elidable=True)]
