# Generated by Django 5.2.3 on 2025-10-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0078_add_twitch_donations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchDonation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'donation',
                    models.OneToOneField(
                        'tracker.Donation',
                        on_delete=models.PROTECT,
                    ),
                ),
                (
                    'twitch_id',
                    models.CharField(
                        help_text='Unique id for this donation',
                        max_length=256,
                        unique=True,
                    ),
                ),
                (
                    'campaign_id',
                    models.CharField(
                        help_text='id for the charity campaign', max_length=128
                    ),
                ),
                (
                    'broadcaster_user_id',
                    models.IntegerField(help_text='Broadcaster id'),
                ),
                (
                    'broadcaster_user_name',
                    models.CharField(
                        help_text="Broadcaster's login name", max_length=128
                    ),
                ),
                (
                    'broadcaster_user_login',
                    models.CharField(
                        help_text="Broadcaster's display name", max_length=128
                    ),
                ),
                ('user_id', models.IntegerField(help_text="Donor's id")),
                (
                    'user_login',
                    models.CharField(help_text="Donor's login name", max_length=128),
                ),
                (
                    'user_name',
                    models.CharField(help_text="Donor's display name", max_length=128),
                ),
                ('charity_name', models.CharField(max_length=128)),
                ('charity_description', models.CharField(max_length=256)),
                ('charity_logo', models.URLField(max_length=128)),
                ('charity_website', models.URLField(max_length=128)),
                (
                    'amount_value',
                    models.IntegerField(help_text='Value in smallest monetary units'),
                ),
                (
                    'amount_decimal_places',
                    models.IntegerField(
                        help_text='actual value = value / 10^decimal_places'
                    ),
                ),
                (
                    'amount_currency',
                    models.CharField(help_text='ISO-4217 code', max_length=3),
                ),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
