# Generated by Django 5.2.3 on 2025-07-06 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0078_add_twitch_donations'),
        ('tracker', '0078_clear_prize_maximumbid'),
    ]

    operations = []
