# Generated by Django 5.2.3 on 2025-07-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0079_merge_20250706_0120'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(
                models.F('amount'),
                condition=models.Q(
                    ('testdonation', False), ('transactionstate', 'COMPLETED')
                ),
                name='amount_completed',
            ),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(
                models.F('amount'),
                models.F('event_id'),
                condition=models.Q(
                    ('testdonation', False), ('transactionstate', 'COMPLETED')
                ),
                name='amount_event_completed',
            ),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(
                models.F('commentstate'),
                models.F('event_id'),
                condition=models.Q(
                    ('testdonation', False), ('transactionstate', 'COMPLETED')
                ),
                name='commentstate_event_completed',
            ),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(
                models.F('readstate'),
                models.F('event_id'),
                condition=models.Q(
                    ('testdonation', False), ('transactionstate', 'COMPLETED')
                ),
                name='readstate_event_completed',
            ),
        ),
    ]
