# Generated by Django 5.2.3 on 2025-07-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0078_clear_prize_maximumbid'),
        ('tracker', '0080_add_donation_indexes'),
    ]

    operations = []
