# Generated by Django 5.2.3 on 2025-07-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0080_add_donation_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                models.F("donor_id"),
                models.F("event_id"),
                condition=models.Q(
                    ("testdonation", False), ("transactionstate", "COMPLETED")
                ),
                name="donor_id_event_completed",
            ),
        ),
    ]
