# Generated by Django 6.0.1 on 2026-03-05 19:48

import tracker.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0081_merge_20250731_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedrun',
            name='original_estimate',
            field=tracker.models.fields.TimestampField(blank=True, null=True, editable=False),
        ),
    ]
