# Generated by Django 6.0.1 on 2026-04-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0081_merge_20250731_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='tags',
            field=models.ManyToManyField(
                blank=True, related_name='bids', to='tracker.tag'
            ),
        ),
    ]
