# Generated by Django 5.2.3 on 2025-10-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0079_add_twitch_donation_table'),
        ('tracker', '0081_merge_20250731_2009'),
    ]

    operations = []
