# Generated by Django 5.2.3 on 2025-09-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0081_merge_20250724_0114'),
        ('tracker', '0081_merge_20250731_2009'),
    ]

    operations = []
