# Generated by Django 6.0.1 on 2026-06-09 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0082_add_bid_tags'),
        ('tracker', '0082_add_original_estimate'),
    ]

    operations = []
