# Generated by Django 6.0.1 on 2026-06-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0079_add_twitch_donation_table'),
        ('tracker', '0083_merge_0082_add_bid_tags_0082_add_original_estimate'),
    ]

    operations = []
