# Generated by Django 6.0.1 on 2026-08-16 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0084_merge_20260618_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='domain',
            field=models.CharField(
                choices=[
                    ('LOCAL', 'Local'),
                    ('CHIPIN', 'ChipIn'),
                    ('PAYPAL', 'PayPal'),
                    ('TWITCH', 'Twitch'),
                    ('BCAUSE', 'bcause'),
                ],
                default='LOCAL',
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name='BcauseDonation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('amount_cents', models.IntegerField(default=0)),
                ('beneficiary_id', models.CharField(blank=True, max_length=64)),
                ('currency_code', models.CharField(blank=True, max_length=8)),
                ('date_valuta_utc', models.DateTimeField(blank=True, null=True)),
                ('donor_name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('fee_cents', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('raw', models.TextField()),
                ('sandbox', models.BooleanField()),
                (
                    'status',
                    models.CharField(
                        choices=[('completed', 'Completed')], max_length=64, null=True
                    ),
                ),
                (
                    'transaction_id',
                    models.CharField(max_length=64, null=True, unique=True),
                ),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                (
                    'donation',
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='tracker.donation',
                    ),
                ),
            ],
        ),
    ]
