# Generated by Django 6.0.1 on 2026-08-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0085_add_bcause_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcausedonation',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='bcause_id',
            field=models.CharField(
                blank=True,
                help_text='The unique user_id returned by the Bcause API for non-anonymous donors',
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='donor',
            name='ineligible',
            field=models.BooleanField(
                default=False, help_text='Whether this donor is ineligible for prizes'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bcausedonation',
            name='sandbox',
            field=models.BooleanField(default=False),
        ),
    ]
